Implement load and save feature
DEIS-Tools/VisuAalWiNes pull request #18
Opened 2020-08-24 14:39 UTC by clemy

Implements a Load/Save feature for Queries and Options. Available via the "Load / Save" button in the Query dialog.
The data is stored in localStorage in the browser. So it is separated for every user. Normal browser settings will keep the data with unlimited lifetime.
It saves the query, the validation options and the weight settings. It does not save view settings.

2020-08-25 07:12 UTC, MortenSchou commented
I think this works really well. 👍 

Small bug: If you save a query with a special character in the name (e.g. ? ! ") then you cannot select (load or delete) it later. 

Maybe a 'rename' feature would be nice. (It can be done now with load, delete, and save with new name, but that is a bit inconvenient.)

2020-08-25 12:27 UTC, MortenSchou approved these changes

2020-08-27 11:19 UTC, MortenSchou commented
I got some comments from Jiri regarding this feature. I also think this would improve it:
- The saved queries should be integrated with the example queries since it is essentially the same thing - the examples are just pre-defined. Eventually, it should be possible (in the offline tool) to save (and modify/delete) the user-made queries alongside the example queries. But more on this, when we get to discuss the new file format...
- In the online demo, it still makes sense to store the custom queries in the browser, but it would be nice if the GUI made this integration seamless with the example queries. (If it is not too difficult).
- Like with the example queries, the query-string of the custom queries should be displayed, while the name (or rather the comment about the query) should be secondary in the GUI.

2020-09-02 12:19 UTC, petergjoel requested changes
Waiting for Jiri's improvements.

2020-11-28 19:41 UTC, clemy commented
Replaced by new pull request.

2020-11-28 19:41 UTC, closed without merging